package com.hltc.mtmap.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hltc.mtmap.orm.model.MTUser;
import com.hltc.mtmap.orm.model.MTFriendStatus;
import com.hltc.mtmap.orm.model.MTGrain;
import com.hltc.mtmap.orm.model.MTSite;
import com.hltc.mtmap.orm.model.MTPhoto;
import com.hltc.mtmap.orm.model.MTCategory;
import com.hltc.mtmap.orm.model.MTComment;
import com.hltc.mtmap.orm.model.MTFavourite;

import com.hltc.mtmap.orm.dao.MTUserDao;
import com.hltc.mtmap.orm.dao.MTFriendStatusDao;
import com.hltc.mtmap.orm.dao.MTGrainDao;
import com.hltc.mtmap.orm.dao.MTSiteDao;
import com.hltc.mtmap.orm.dao.MTPhotoDao;
import com.hltc.mtmap.orm.dao.MTCategoryDao;
import com.hltc.mtmap.orm.dao.MTCommentDao;
import com.hltc.mtmap.orm.dao.MTFavouriteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mTUserDaoConfig;
    private final DaoConfig mTFriendStatusDaoConfig;
    private final DaoConfig mTGrainDaoConfig;
    private final DaoConfig mTSiteDaoConfig;
    private final DaoConfig mTPhotoDaoConfig;
    private final DaoConfig mTCategoryDaoConfig;
    private final DaoConfig mTCommentDaoConfig;
    private final DaoConfig mTFavouriteDaoConfig;

    private final MTUserDao mTUserDao;
    private final MTFriendStatusDao mTFriendStatusDao;
    private final MTGrainDao mTGrainDao;
    private final MTSiteDao mTSiteDao;
    private final MTPhotoDao mTPhotoDao;
    private final MTCategoryDao mTCategoryDao;
    private final MTCommentDao mTCommentDao;
    private final MTFavouriteDao mTFavouriteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mTUserDaoConfig = daoConfigMap.get(MTUserDao.class).clone();
        mTUserDaoConfig.initIdentityScope(type);

        mTFriendStatusDaoConfig = daoConfigMap.get(MTFriendStatusDao.class).clone();
        mTFriendStatusDaoConfig.initIdentityScope(type);

        mTGrainDaoConfig = daoConfigMap.get(MTGrainDao.class).clone();
        mTGrainDaoConfig.initIdentityScope(type);

        mTSiteDaoConfig = daoConfigMap.get(MTSiteDao.class).clone();
        mTSiteDaoConfig.initIdentityScope(type);

        mTPhotoDaoConfig = daoConfigMap.get(MTPhotoDao.class).clone();
        mTPhotoDaoConfig.initIdentityScope(type);

        mTCategoryDaoConfig = daoConfigMap.get(MTCategoryDao.class).clone();
        mTCategoryDaoConfig.initIdentityScope(type);

        mTCommentDaoConfig = daoConfigMap.get(MTCommentDao.class).clone();
        mTCommentDaoConfig.initIdentityScope(type);

        mTFavouriteDaoConfig = daoConfigMap.get(MTFavouriteDao.class).clone();
        mTFavouriteDaoConfig.initIdentityScope(type);

        mTUserDao = new MTUserDao(mTUserDaoConfig, this);
        mTFriendStatusDao = new MTFriendStatusDao(mTFriendStatusDaoConfig, this);
        mTGrainDao = new MTGrainDao(mTGrainDaoConfig, this);
        mTSiteDao = new MTSiteDao(mTSiteDaoConfig, this);
        mTPhotoDao = new MTPhotoDao(mTPhotoDaoConfig, this);
        mTCategoryDao = new MTCategoryDao(mTCategoryDaoConfig, this);
        mTCommentDao = new MTCommentDao(mTCommentDaoConfig, this);
        mTFavouriteDao = new MTFavouriteDao(mTFavouriteDaoConfig, this);

        registerDao(MTUser.class, mTUserDao);
        registerDao(MTFriendStatus.class, mTFriendStatusDao);
        registerDao(MTGrain.class, mTGrainDao);
        registerDao(MTSite.class, mTSiteDao);
        registerDao(MTPhoto.class, mTPhotoDao);
        registerDao(MTCategory.class, mTCategoryDao);
        registerDao(MTComment.class, mTCommentDao);
        registerDao(MTFavourite.class, mTFavouriteDao);
    }

    public void clear() {
        mTUserDaoConfig.getIdentityScope().clear();
        mTFriendStatusDaoConfig.getIdentityScope().clear();
        mTGrainDaoConfig.getIdentityScope().clear();
        mTSiteDaoConfig.getIdentityScope().clear();
        mTPhotoDaoConfig.getIdentityScope().clear();
        mTCategoryDaoConfig.getIdentityScope().clear();
        mTCommentDaoConfig.getIdentityScope().clear();
        mTFavouriteDaoConfig.getIdentityScope().clear();
    }

    public MTUserDao getMTUserDao() {
        return mTUserDao;
    }

    public MTFriendStatusDao getMTFriendStatusDao() {
        return mTFriendStatusDao;
    }

    public MTGrainDao getMTGrainDao() {
        return mTGrainDao;
    }

    public MTSiteDao getMTSiteDao() {
        return mTSiteDao;
    }

    public MTPhotoDao getMTPhotoDao() {
        return mTPhotoDao;
    }

    public MTCategoryDao getMTCategoryDao() {
        return mTCategoryDao;
    }

    public MTCommentDao getMTCommentDao() {
        return mTCommentDao;
    }

    public MTFavouriteDao getMTFavouriteDao() {
        return mTFavouriteDao;
    }

}
