package com.hltc.mtmap.orm;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.hltc.mtmap.MTGrain;
import com.hltc.mtmap.MTUser;

import com.hltc.mtmap.MTFavourite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table MTFAVOURITE.
 */
public class MTFavouriteDao extends AbstractDao<MTFavourite, Long> {

    public static final String TABLENAME = "MTFAVOURITE";
    private DaoSession daoSession;
    ;
    private Query<MTFavourite> mTUser_Favourite2UserQuery;
    private Query<MTFavourite> mTGrain_Favourites2GrainQuery;
    private String selectDeep;

    public MTFavouriteDao(DaoConfig config) {
        super(config);
    }

    public MTFavouriteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MTFAVOURITE' (" + //
                "'_id' INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "'USER_ID' INTEGER NOT NULL ," + // 1: userId
                "'GRAIN_ID' INTEGER NOT NULL );"); // 2: grainId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MTFAVOURITE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MTFavourite entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getGrainId());
    }

    @Override
    protected void attachEntity(MTFavourite entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public MTFavourite readEntity(Cursor cursor, int offset) {
        MTFavourite entity = new MTFavourite( //
                cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // userId
                cursor.getLong(offset + 2) // grainId
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MTFavourite entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setGrainId(cursor.getLong(offset + 2));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MTFavourite entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(MTFavourite entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    /** Internal query to resolve the "favourite2User" to-many relationship of MTUser. */
    public List<MTFavourite> _queryMTUser_Favourite2User(long userId) {
        synchronized (this) {
            if (mTUser_Favourite2UserQuery == null) {
                QueryBuilder<MTFavourite> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                mTUser_Favourite2UserQuery = queryBuilder.build();
            }
        }
        Query<MTFavourite> query = mTUser_Favourite2UserQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    /** Internal query to resolve the "favourites2Grain" to-many relationship of MTGrain. */
    public List<MTFavourite> _queryMTGrain_Favourites2Grain(long grainId) {
        synchronized (this) {
            if (mTGrain_Favourites2GrainQuery == null) {
                QueryBuilder<MTFavourite> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GrainId.eq(null));
                mTGrain_Favourites2GrainQuery = queryBuilder.build();
            }
        }
        Query<MTFavourite> query = mTGrain_Favourites2GrainQuery.forCurrentThread();
        query.setParameter(0, grainId);
        return query.list();
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMTUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMTGrainDao().getAllColumns());
            builder.append(" FROM MTFAVOURITE T");
            builder.append(" LEFT JOIN MTUSER T0 ON T.'USER_ID'=T0.'USER_ID'");
            builder.append(" LEFT JOIN MTGRAIN T1 ON T.'GRAIN_ID'=T1.'GRAIN_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected MTFavourite loadCurrentDeep(Cursor cursor, boolean lock) {
        MTFavourite entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        MTUser mTUser = loadCurrentOther(daoSession.getMTUserDao(), cursor, offset);
        if(mTUser != null) {
            entity.setMTUser(mTUser);
        }
        offset += daoSession.getMTUserDao().getAllColumns().length;

        MTGrain mTGrain = loadCurrentOther(daoSession.getMTGrainDao(), cursor, offset);
        if(mTGrain != null) {
            entity.setMTGrain(mTGrain);
        }

        return entity;
    }
    
    public MTFavourite loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MTFavourite> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MTFavourite> list = new ArrayList<MTFavourite>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MTFavourite> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MTFavourite> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
    
/**
     * Properties of entity MTFavourite.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property GrainId = new Property(2, long.class, "grainId", false, "GRAIN_ID");
    }
 
}
