package com.hltc.mtmap;

import java.util.List;

import com.hltc.mtmap.orm.DaoSession;

import de.greenrobot.dao.DaoException;

import com.hltc.mtmap.orm.MTGrainDao;
import com.hltc.mtmap.orm.MTSiteDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table MTSITE.
 */
public class MTSite {

    /**
     * Not-null value.
     */
    private String siteId;
    private String name;
    private String address;
    private Double lat;
    private Double lon;
    private String phone;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient MTSiteDao myDao;

    private List<MTGrain> grains2Site;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MTSite() {
    }

    public MTSite(String siteId) {
        this.siteId = siteId;
    }

    public MTSite(String siteId, String name, String address, Double lat, Double lon, String phone) {
        this.siteId = siteId;
        this.name = name;
        this.address = address;
        this.lat = lat;
        this.lon = lon;
        this.phone = phone;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMTSiteDao() : null;
    }

    /**
     * Not-null value.
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<MTGrain> getGrains2Site() {
        if (grains2Site == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MTGrainDao targetDao = daoSession.getMTGrainDao();
            List<MTGrain> grains2SiteNew = targetDao._queryMTSite_Grains2Site(siteId);
            synchronized (this) {
                if (grains2Site == null) {
                    grains2Site = grains2SiteNew;
                }
            }
        }
        return grains2Site;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetGrains2Site() {
        grains2Site = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
