package com.hltc.mtmap.orm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hltc.mtmap.orm.model.MTUser;
import com.hltc.mtmap.orm.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MTUSER.
*/
public class MTUserDao extends AbstractDao<MTUser, Long> {

    public static final String TABLENAME = "MTUSER";
    private DaoSession daoSession;
    ;

    public MTUserDao(DaoConfig config) {
        super(config);
    }


    public MTUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MTUSER' (" + //
                "'USER_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: userId
                "'NICK_NAME' TEXT NOT NULL ," + // 1: nickName
                "'CREATE_TIME' TEXT NOT NULL ," + // 2: createTime
                "'PHONE' TEXT NOT NULL ," + // 3: phone
                "'PORTRAIT' TEXT NOT NULL ," + // 4: portrait
                "'COVER_IMG' TEXT NOT NULL ," + // 5: coverImg
                "'SIGNATURE' TEXT NOT NULL );"); // 6: signature
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MTUSER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MTUser entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getUserId());
        stmt.bindString(2, entity.getNickName());
        stmt.bindString(3, entity.getCreateTime());
        stmt.bindString(4, entity.getPhone());
        stmt.bindString(5, entity.getPortrait());
        stmt.bindString(6, entity.getCoverImg());
        stmt.bindString(7, entity.getSignature());
    }

    @Override
    protected void attachEntity(MTUser entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public MTUser readEntity(Cursor cursor, int offset) {
        MTUser entity = new MTUser( //
                cursor.getLong(offset + 0), // userId
                cursor.getString(offset + 1), // nickName
                cursor.getString(offset + 2), // createTime
            cursor.getString(offset + 3), // phone
                cursor.getString(offset + 4), // portrait
                cursor.getString(offset + 5), // coverImg
                cursor.getString(offset + 6) // signature
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MTUser entity, int offset) {
        entity.setUserId(cursor.getLong(offset + 0));
        entity.setNickName(cursor.getString(offset + 1));
        entity.setCreateTime(cursor.getString(offset + 2));
        entity.setPhone(cursor.getString(offset + 3));
        entity.setPortrait(cursor.getString(offset + 4));
        entity.setCoverImg(cursor.getString(offset + 5));
        entity.setSignature(cursor.getString(offset + 6));
     }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MTUser entity, long rowId) {
        entity.setUserId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MTUser entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity MTUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, long.class, "userId", true, "USER_ID");
        public final static Property NickName = new Property(1, String.class, "nickName", false, "NICK_NAME");
        public final static Property CreateTime = new Property(2, String.class, "createTime", false, "CREATE_TIME");
        public final static Property Phone = new Property(3, String.class, "phone", false, "PHONE");
        public final static Property Portrait = new Property(4, String.class, "portrait", false, "PORTRAIT");
        public final static Property CoverImg = new Property(5, String.class, "coverImg", false, "COVER_IMG");
        public final static Property Signature = new Property(6, String.class, "signature", false, "SIGNATURE");
    }

}
